name: Keep Render & Web Alive

on:
  schedule:
    # Jalan tiap 10 menit sekali
    - cron: '*/10 * * * *'
  workflow_dispatch: # Pemicu manual kalau mau tes

jobs:
  ping-services:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Backend & Main Website
        env:
          PING: ${{ secrets.PING }}
          WEB_URL: ${{ secrets.WEB_URL }}
        run: |
          echo "Pinging Backend Render..."
          curl -s "$PING" || exit 0

          echo "Pinging Main Website..."
          curl -s "https://nimedesu.vercel.app" || exit 0

          echo "Pinging..."
          curl -s "$KETUMBAR" || exit 0
